/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-05-26 03:18:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class itemAbout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/mealKit_webSite/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TeamProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/mealKit_webSite/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TeamProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1651802072000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>이젠, 집에서 | 회원가입</title>\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"https://cdn.iamport.kr/js/iamport.payment-1.1.5.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(\r\n");
      out.write("		function() {\r\n");
      out.write("			var check = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ilist[0].item_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("			if(check == \"\"){\r\n");
      out.write("				alert(\"유효하지 않은 페이지입니다.\");\r\n");
      out.write("				history.back();\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("$(document).ready(\r\n");
      out.write("		function() {\r\n");
      out.write("			var check = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ilist[0].item_quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("			if(check == 0){\r\n");
      out.write("				alert(\"품절된 상품입니다.\");\r\n");
      out.write("				history.back();\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	$(document).ready(\r\n");
      out.write("			function() {\r\n");
      out.write("				\r\n");
      out.write("				var price = $('#price').val();\r\n");
      out.write("				var cnt = $('#cnt').val();\r\n");
      out.write("\r\n");
      out.write("				var total_price = price * cnt;\r\n");
      out.write("				$('#total_price').text(\r\n");
      out.write("						total_price.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g,\r\n");
      out.write("								','));\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(\r\n");
      out.write("			function() {\r\n");
      out.write("				$('#cnt').click(\r\n");
      out.write("						function() {\r\n");
      out.write("							var price = $('#price').val();\r\n");
      out.write("							var cnt = $('#cnt').val();\r\n");
      out.write("							var total_price = price * cnt;\r\n");
      out.write("							$('#total_price').text(\r\n");
      out.write("									total_price.toString().replace(\r\n");
      out.write("											/\\B(?=(\\d{3})+(?!\\d))/g, ','));\r\n");
      out.write("						});\r\n");
      out.write("			});\r\n");
      out.write("	$(document).ready(\r\n");
      out.write("			function() {\r\n");
      out.write("				$('#cnt').keyup(\r\n");
      out.write("						function() {\r\n");
      out.write("							var price = $('#price').val();\r\n");
      out.write("							var cnt = $('#cnt').val();\r\n");
      out.write("							var total_price = price * cnt;\r\n");
      out.write("							$('#total_price').text(\r\n");
      out.write("									total_price.toString().replace(\r\n");
      out.write("											/\\B(?=(\\d{3})+(?!\\d))/g, ','));\r\n");
      out.write("						});\r\n");
      out.write("			});\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write(".login-container {\r\n");
      out.write("	width: 500px;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	padding: 70px 20px;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login--title {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-input {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	margin: 10px 0;\r\n");
      out.write("	border: 1px solid #efefef;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-input:focus {\r\n");
      out.write("	box-shadow: 3px 3px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-input--title {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	display: block;\r\n");
      out.write("	margin: 5px 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-btn {\r\n");
      out.write("	border: 0;\r\n");
      out.write("	display: block;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	background-color: #fd7e14;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	margin: 5px 0;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-btn:hover {\r\n");
      out.write("	background-color: #FF9900;\r\n");
      out.write("	box-shadow: 3px 3px 3px rgba(0, 0, 0, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Menu {\r\n");
      out.write(" 	display: flex; \r\n");
      out.write("	justify-content: space-evenly;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	width: 60%;\r\n");
      out.write("	align: center;\r\n");
      out.write("	margin-left: auto;\r\n");
      out.write("	margin-right: auto;\r\n");
      out.write("	border:2px solid gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Menu a {\r\n");
      out.write("	color: black;\r\n");
      out.write("	font-size: 32px;\r\n");
      out.write("	padding: 5px 5px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Fixed {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 0px;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	left: 50%;\r\n");
      out.write("	transform: translate(-50%, 0); @media ( max-width :480px) { .Menu a {\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		var Offset = $('.Menu').offset();\r\n");
      out.write("		$(window).scroll(function() {\r\n");
      out.write("			if ($(document).scrollTop() > Offset.top) {\r\n");
      out.write("				$('.Menu').addClass('Fixed');\r\n");
      out.write("			} else {\r\n");
      out.write("				$('.Menu').removeClass('Fixed');\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "nav.jsp", out, false);
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<div style=\"width: 60%; margin-left: auto; margin-right: auto;\"\r\n");
      out.write("		align=\"center\">\r\n");
      out.write("		<div style=\"width: 60%; float: left;\">\r\n");
      out.write("			<img width=\"70%\" height=\"70%\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ilist[0].item_pictureUrl1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div style=\"width: 40%; float: left;\" align=\"left\">\r\n");
      out.write("			<form action=\"cartinsert.do\" method=\"post\">\r\n");
      out.write("				<p>[");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ilist[0].item_category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("]</p>\r\n");
      out.write("				<p>\r\n");
      out.write("					<strong><h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ilist[0].item_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2></strong>\r\n");
      out.write("				</p>\r\n");
      out.write("				<p style=\"color:gray\">\r\n");
      out.write("					");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ilist[0].item_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("				</p>\r\n");
      out.write("				<hr>\r\n");
      out.write("				<p>");
      if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_page_context))
        return;
      out.write("원</p>\r\n");
      out.write("				<p style=\"color:green\">\r\n");
      out.write("					[구매 혜택 / 적립포인트 (개당) +\r\n");
      out.write("					");
      if (_jspx_meth_fmt_005fformatNumber_005f1(_jspx_page_context))
        return;
      out.write("p]\r\n");
      out.write("				</p>\r\n");
      out.write("				<hr>\r\n");
      out.write("				<p>몇인분 :");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ilist[0].item_total}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("인분</p>\r\n");
      out.write("				<p>조리시간 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ilist[0].item_time}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("분</p>\r\n");
      out.write("				<p>\r\n");
      out.write("					수량 : <input type=\"number\" name='item_cnt' id=\"cnt\" value=\"1\" min=\"1\"\r\n");
      out.write("						max=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ilist[0].item_quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				</p>\r\n");
      out.write("				<p>\r\n");
      out.write("					남은 수량 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ilist[0].item_quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("				</p>\r\n");
      out.write("				<p>\r\n");
      out.write("					총 합계 금액 <span id=\"total_price\"></span>원\r\n");
      out.write("				</p>\r\n");
      out.write("				<input type=\"hidden\" name=\"item_quantity\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ilist[0].item_quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"item_num\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ilist[0].item_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"item_pictureUrl1\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ilist[0].item_pictureUrl1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"item_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ilist[0].item_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"item_price\"\r\n");
      out.write("					value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ilist[0].item_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <input type=\"submit\"\r\n");
      out.write("					class=\"form-btn\" value=\"장바구니\" id=\"cart\">\r\n");
      out.write("			</form>\r\n");
      out.write("			<!-- 가격 자동 계산용 -->\r\n");
      out.write("			<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ilist[0].item_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"price\">\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"Menu\">\r\n");
      out.write("		<a href=\"#info\">상세정보</a> <a href=\"#review\">후기</a> <a href=\"#qna\">문의</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"info\"\r\n");
      out.write("		align=\"center\">\r\n");
      out.write("		<br> <br> <br> <br> <br> <img\r\n");
      out.write("			src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ilist[0].item_pictureUrl2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"review\"\r\n");
      out.write("		style=\"width: 60%; margin-left: auto; margin-right: auto;\"\r\n");
      out.write("		align=\"center\">\r\n");
      out.write("		<br> <br> <br> <br> <br>\r\n");
      out.write("		<div align=\"left\">\r\n");
      out.write("			<h1>후기</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("		<hr>\r\n");
      out.write("		a<br> a<br> a<br> a<br> a<br> a<br> a<br>\r\n");
      out.write("		a<br> a<br> a<br> a<br> a<br> a<br> a<br>\r\n");
      out.write("		a<br> a<br> a<br> a<br> a<br> a<br> a<br>\r\n");
      out.write("		a<br> a<br> a<br> a<br> a<br> a<br> a<br>\r\n");
      out.write("		a<br> a<br> a<br> a<br> a<br> a<br> a<br>\r\n");
      out.write("		a<br> a<br> a<br> a<br> a<br> a<br> a<br>\r\n");
      out.write("		a<br> a<br> a<br> a<br> a<br> a<br> a<br>\r\n");
      out.write("		a<br> a<br> a<br> a<br> a<br> a<br> a<br>\r\n");
      out.write("		a<br> a<br> a<br> a<br> a<br> a<br> a<br>\r\n");
      out.write("		a<br> a<br> a<br> a<br> a<br> a<br> a<br>\r\n");
      out.write("		a<br> a<br>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"qna\"\r\n");
      out.write("		style=\"width: 60%; margin-left: auto; margin-right: auto;\"\r\n");
      out.write("		align=\"center\">\r\n");
      out.write("		<br> <br> <br> <br> <br> <br>\r\n");
      out.write("		<div align=\"left\">\r\n");
      out.write("			<h1>문의</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("		<hr>\r\n");
      out.write("		a<br> a<br> a<br> a<br> a<br> a<br> a<br>\r\n");
      out.write("		a<br> a<br> a<br> a<br> a<br> a<br> a<br>\r\n");
      out.write("		a<br> a<br> a<br> a<br> a<br> a<br> a<br>\r\n");
      out.write("		a<br> a<br> a<br> a<br> a<br> a<br> a<br>\r\n");
      out.write("		a<br> a<br> a<br> a<br> a<br> a<br>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
      // /itemAbout.jsp(188,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ilist[0].item_price}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f1.setParent(null);
      // /itemAbout.jsp(191,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ilist[0].item_price*0.05}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
      _jspx_th_fmt_005fformatNumber_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
    }
    return false;
  }
}
