/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-05-29 14:54:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class nav_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("  		<link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\" rel=\"stylesheet\" />\r\n");
      out.write("        <!-- Favicon-->\r\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\" />\r\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("        <link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("        <!-- Bootstrap core JS-->\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"js/scripts.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

	String name = null;
	String userid = null;
	String pw = null;
	String email = null;
	String phone = null;
	String addr = null;
	int admin = 0;
	int cartcnt = 0;
	int addrcnt = 0;
	int point = 0;
	
	if(session.getAttribute("name") != null){
		name = (String) session.getAttribute("name");
		userid = (String) session.getAttribute("userid");
		pw = (String) session.getAttribute("pw");
		email = (String) session.getAttribute("email");
		phone = (String) session.getAttribute("phone");
		admin = (int) session.getAttribute("admin");
		cartcnt = (int) session.getAttribute("cartcnt");
		addrcnt = (int) session.getAttribute("addrcnt");
		addr = (String) session.getAttribute("addr");
		point = (int) session.getAttribute("point");
	}
	
	
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("            <div class=\"container px-4 px-lg-5\">\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"itemmain.do\">이젠, 집에서</a>\r\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"><span class=\"navbar-toggler-icon\"></span></button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("                    <ul class=\"navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4\">\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"about.jsp\">사이트 소개</a></li>\r\n");
      out.write("                        <li class=\"nav-item dropdown\">\r\n");
      out.write("                            <a class=\"nav-link dropdown-toggle\" id=\"navbarDropdown\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">게시판</a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"#!\">공지사항</a></li>\r\n");
      out.write("                                <li><hr class=\"dropdown-divider\" /></li>\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"#!\">문의하기</a></li>\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"#!\">자주묻는 질문</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item dropdown\">\r\n");
      out.write("                            <a class=\"nav-link dropdown-toggle\" id=\"navbarDropdown\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">밀키트</a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"itemlist.do?view=card&pageSize=12&check=all&category=empty&priceSort=default&keyword=\">전체 밀키트</a></li>\r\n");
      out.write("                                <li><hr class=\"dropdown-divider\" /></li>\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"itemlist.do?view=card&pageSize=12&check=best&category=empty&priceSort=default&keyword=\">인기 밀키트</a></li>\r\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"itemlist.do?view=card&pageSize=12&check=new&category=empty&priceSort=default&keyword=\">신상 밀키트</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    &nbsp;&nbsp;&nbsp;\r\n");
      out.write("                    ");
if(name != null){ 
      out.write("\r\n");
      out.write("	                <form action =\"myPage.jsp\" class=\"d-flex\">\r\n");
      out.write("	                    <button class=\"btn btn-outline-dark\" type=\"submit\">\r\n");
      out.write("	                            	마이페이지\r\n");
      out.write("	                    </button>\r\n");
      out.write("	                </form>\r\n");
      out.write("	                <br>\r\n");
      out.write("	                <form action=\"cartlist.do\" class=\"d-flex\">\r\n");
      out.write("                        <button id=\"cartbtn\" class=\"btn btn-outline-dark\" type=\"submit\">\r\n");
      out.write("						<i class=\"bi-cart-fill me-1\"></i>\r\n");
      out.write("                            	장바구니\r\n");
      out.write("                            <span class=\"badge bg-dark text-white ms-1 rounded-pill\">");
      out.print(cartcnt);
      out.write(" <!-- 장바구니에 담긴 수 --></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </form>\r\n");
      out.write("	                <br>\r\n");
      out.write("                    <form action =\"logout.jsp\" class=\"d-flex\">\r\n");
      out.write("                        <button class=\"btn btn-outline-dark\" type=\"submit\">\r\n");
      out.write("                            		로그아웃\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </form>    \r\n");
      out.write("	                    ");
if(admin == 1){ 
      out.write("\r\n");
      out.write("	                    <form action =\"managePage.jsp\" class=\"d-flex\">\r\n");
      out.write("	                        <button class=\"btn btn-outline-dark\" type=\"submit\">\r\n");
      out.write("	                            	관리자페이지\r\n");
      out.write("	                        </button>\r\n");
      out.write("	                    </form>\r\n");
      out.write("	                    \r\n");
      out.write("	                    ");
} 
      out.write("      \r\n");
      out.write("                    ");
} else { 
      out.write("\r\n");
      out.write("                    <form action =\"login.jsp\" class=\"d-flex\">\r\n");
      out.write("                        <button class=\"btn btn-outline-dark\" type=\"submit\">\r\n");
      out.write("                            	로그인/회원가입</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    ");
} 
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
