/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-05-16 10:46:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");

    
    request.setCharacterEncoding("UTF-8");
    String item_name = null;
    int etc = (int) session.getAttribute("cartcnt")-1;
    String userid = request.getParameter("userid");
    String deli_name = request.getParameter("deli_name");
    String email = request.getParameter("email");
    String deli_phone = request.getParameter("deli_phone");
    String deli_addr = request.getParameter("deli_postcode")+" "+ request.getParameter("deli_addr1") +", "+ request.getParameter("deli_addr2");
    String deli_postcode = request.getParameter("deli_postcode");
    String deli_pwd = request.getParameter("deli_pwd");
    String deli_msg = request.getParameter("deli_msg");
    String deli_status = request.getParameter("deli_status");
    
    
    int total_price = Integer.parseInt(request.getParameter("total_price"));
    int usePoint =  Integer.parseInt(request.getParameter("usePoint"));
    int amount = total_price - usePoint;
    
    int point = Integer.parseInt(request.getParameter("point"));
    
    if(etc == 0){
    item_name = request.getParameter("item_name");
    }else{
    item_name = request.getParameter("item_name")+" 외 "+etc+" 건";
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>이젠, 집에서 | 회원가입</title>\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-1.12.4.min.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.iamport.kr/js/iamport.payment-1.1.5.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "nav.jsp", out, false);
      out.write("\r\n");
      out.write("아이디:");
      out.print(userid );
      out.write("<br>\r\n");
      out.write("배송받을 이름:");
      out.print(deli_name);
      out.write("<br>\r\n");
      out.write("이메일:");
      out.print(email);
      out.write("<br>\r\n");
      out.write("연락처:");
      out.print(deli_phone);
      out.write("<br>\r\n");
      out.write("우편번호");
      out.print(deli_postcode);
      out.write("\r\n");
      out.write("배송지:");
      out.print(deli_addr);
      out.write("<br>\r\n");
      out.write("공동현관:");
      out.print(deli_pwd);
      out.write("<br>\r\n");
      out.write("배송메세지:");
      out.print(deli_msg);
      out.write("<br>\r\n");
      out.write("배송상태:");
      out.print(deli_status);
      out.write("<br>\r\n");
      out.write("상품명:");
      out.print(item_name);
      out.write("<br>\r\n");
      out.write("외 ~건:");
      out.print(etc);
      out.write("<br>\r\n");
      out.write("적립금:");
      out.print(point);
      out.write("<br>\r\n");
      out.write("총 금액:");
      out.print(total_price);
      out.write("<br>\r\n");
      out.write("사용할 적립금:");
      out.print(usePoint);
      out.write("<br>\r\n");
      out.write("최종 구매금액 :");
      out.print(amount);
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    $(function(){\r\n");
      out.write("        var IMP = window.IMP; // 생략가능\r\n");
      out.write("        IMP.init('imp79971809'); // \"가맹점 식별코드\"\r\n");
      out.write("        var msg;\r\n");
      out.write("        \r\n");
      out.write("        IMP.request_pay({\r\n");
      out.write("            pg : 'kakaopay',\r\n");
      out.write("            pay_method : 'card',\r\n");
      out.write("            merchant_uid : 'merchant_' + new Date().getTime(),\r\n");
      out.write("            name : '이젠, 집에서) ");
      out.print(item_name);
      out.write("',\r\n");
      out.write("            amount : ");
      out.print(amount);
      out.write(",\r\n");
      out.write("            buyer_name : '");
      out.print(deli_name);
      out.write("',\r\n");
      out.write("            buyer_tel : '");
      out.print(deli_phone);
      out.write("',\r\n");
      out.write("            buyer_postcode : '");
      out.print(deli_postcode);
      out.write("', //우편번호 임시\r\n");
      out.write("            buyer_addr : '");
      out.print(deli_addr);
      out.write("',\r\n");
      out.write("        }, function(rsp) {\r\n");
      out.write("            if ( rsp.success ) {\r\n");
      out.write("                jQuery.ajax({\r\n");
      out.write("                    url: \"/payments/complete\",\r\n");
      out.write("                    type: 'POST',\r\n");
      out.write("                    dataType: 'json',\r\n");
      out.write("                    data: {\r\n");
      out.write("                        imp_uid : rsp.imp_uid\r\n");
      out.write("                        //기타 필요한 데이터가 있으면 추가 전달\r\n");
      out.write("                    }\r\n");
      out.write("                })\r\n");
      out.write("                //성공시 이동할 페이지\r\n");
      out.write("               var deli_pwd_encode = encodeURIComponent('");
      out.print(deli_pwd);
      out.write("');\r\n");
      out.write("               location.href='http://localhost:8080/TeamProject/purchaseok.do?userid=");
      out.print(userid);
      out.write("&item_name=");
      out.print(item_name);
      out.write("&total_price=");
      out.print(amount);
      out.write("&deli_name=");
      out.print(deli_name);
      out.write("&deli_addr=");
      out.print(deli_addr);
      out.write("&deli_phone=");
      out.print(deli_phone);
      out.write("&deli_msg=");
      out.print(deli_msg);
      out.write("&deli_pwd='+deli_pwd_encode+'&deli_status=");
      out.print(deli_status);
      out.write("&usePoint=");
      out.print(usePoint);
      out.write("&point=");
      out.print(point);
      out.write("';\r\n");
      out.write("               \r\n");
      out.write("            } else {\r\n");
      out.write("                msg = '결제에 실패하였습니다. 장바구니로 돌아갑니다.';\r\n");
      out.write("                msg += '에러내용 : ' + rsp.error_msg;\r\n");
      out.write("                //실패시 이동할 페이지\r\n");
      out.write("                 location.href='http://localhost:8080/TeamProject/cartlist.do';\r\n");
      out.write("                alert(msg);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("  \r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
