/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-05-26 02:35:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;

public final class purchase_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/mealKit_webSite/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TeamProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/mealKit_webSite/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TeamProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1651802072000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fstep_005fitems_005fend_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fparseNumber_0026_005fvar_005fvalue_005fintegerOnly_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fstep_005fitems_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fparseNumber_0026_005fvar_005fvalue_005fintegerOnly_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fstep_005fitems_005fend_005fbegin.release();
    _005fjspx_005ftagPool_005ffmt_005fparseNumber_0026_005fvar_005fvalue_005fintegerOnly_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 String addr = (String)session.getAttribute("addr");

String postcode = addr.substring(1,6);
String addr1 = addr.substring(8,addr.lastIndexOf(","));
String addr2 = addr.substring(addr.lastIndexOf(",")+2);


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/member.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function setDisplay(){\r\n");
      out.write("    if($('input:radio[id=deli2]').is(':checked')){\r\n");
      out.write("        $('#divId').hide();\r\n");
      out.write("		$(\"input:text[name=deli_pwd]\").val(\"\");\r\n");
      out.write("    }else{\r\n");
      out.write("        $('#divId').show();\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("function modalDisplay1(){\r\n");
      out.write("        $('#recent').hide();\r\n");
      out.write("        $('#manage').show();\r\n");
      out.write("}\r\n");
      out.write("function modalDisplay2(){\r\n");
      out.write("        $('#manage').hide();\r\n");
      out.write("        $('#recent').show();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("	  $(\"input:radio[name=addrCheck]\").click(function(){\r\n");
      out.write("	    if($(\"input[name=addrCheck]:checked\").val() == \"0\"){\r\n");
      out.write("			$(\"input:text[name=deli_name]\").val(\"");
      out.print(session.getAttribute("name"));
      out.write("\");\r\n");
      out.write("			$(\"input:text[name=deli_name]\").attr(\"readonly\",true);\r\n");
      out.write("			$(\"input:text[name=deli_postcode]\").val(\"");
      out.print(postcode);
      out.write("\");\r\n");
      out.write("			$(\"input:text[name=deli_postcode]\").attr(\"readonly\",true);\r\n");
      out.write("			$(\"input:text[name=deli_addr1]\").val(\"");
      out.print(addr1);
      out.write("\");\r\n");
      out.write("			$(\"input:text[name=deli_addr1]\").attr(\"readonly\",true);\r\n");
      out.write("			$(\"input:text[name=deli_addr2]\").val(\"");
      out.print(addr2);
      out.write("\");\r\n");
      out.write("			$(\"input:text[name=deli_addr2]\").attr(\"readonly\",true);\r\n");
      out.write("			$(\"input:text[name=deli_phone]\").val(\"");
      out.print(session.getAttribute("phone"));
      out.write("\");\r\n");
      out.write("			$(\"input:text[name=deli_phone]\").attr(\"readonly\",true);\r\n");
      out.write("			$(\"input:text[name=deli_msg]\").val(\"\");\r\n");
      out.write("			$(\"input:text[name=deli_pwd]\").val(\"\");\r\n");
      out.write("			\r\n");
      out.write("		  const target = document.getElementById('daumPostCode');\r\n");
      out.write("		  target.disabled = true;\r\n");
      out.write("		  \r\n");
      out.write("			\r\n");
      out.write("	    } else if($(\"input[name=addrCheck]:checked\").val() == \"1\"){\r\n");
      out.write("			$(\"input:text[name=deli_name]\").val(\"\");\r\n");
      out.write("			$(\"input:text[name=deli_name]\").attr(\"readonly\",false);	      \r\n");
      out.write("			$(\"input:text[name=deli_postcode]\").val(\"\");\r\n");
      out.write("			$(\"input:text[name=deli_postcode]\").attr(\"readonly\",false);	      \r\n");
      out.write("			$(\"input:text[name=deli_addr1]\").val(\"\");\r\n");
      out.write("			$(\"input:text[name=deli_addr1]\").attr(\"readonly\",false);	      \r\n");
      out.write("			$(\"input:text[name=deli_addr2]\").val(\"\");\r\n");
      out.write("			$(\"input:text[name=deli_addr2]\").attr(\"readonly\",false);	      \r\n");
      out.write("			$(\"input:text[name=deli_phone]\").val(\"\");\r\n");
      out.write("			$(\"input:text[name=deli_phone]\").attr(\"readonly\",false);	 \r\n");
      out.write("			$(\"input:text[name=deli_msg]\").val(\"\");\r\n");
      out.write("			$(\"input:text[name=deli_pwd]\").val(\"\");\r\n");
      out.write("		  const target = document.getElementById('daumPostCode');\r\n");
      out.write("		  target.disabled = false;\r\n");
      out.write("		  \r\n");
      out.write("	    }\r\n");
      out.write("	  });\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("// 페이지 로드시 사용할 포인트, 최종금액 표시되게끔. 이게 없으면 빈칸으로 나타나고, \r\n");
      out.write("// 아래에 있는 keyup 이벤트가 활성화돼야 그때 값이 들어감\r\n");
      out.write("$( document ).ready( function() {\r\n");
      out.write("	var a = $( '#a' ).val();\r\n");
      out.write("    var b = $( '#usePoint' ).val();\r\n");
      out.write("\r\n");
      out.write("    var ab = a - b + 3000;\r\n");
      out.write("    $( '#ab' ).text( ab.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ',') );\r\n");
      out.write("    $( '#usePointResult' ).text( b.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ',') );\r\n");
      out.write("    } );\r\n");
      out.write(" \r\n");
      out.write("$( document ).ready( function() {\r\n");
      out.write("    $( '#a, #usePoint' ).keyup ( function() {\r\n");
      out.write("      var a = Number($( '#a' ).val());\r\n");
      out.write("      var b = $( '#usePoint' ).val();\r\n");
      out.write("		var message = \"\";\r\n");
      out.write("	      if(a<b){\r\n");
      out.write("	  	 	b = a;\r\n");
      out.write("	  	 	message = \"상품 가격보다 클 수 없습니다.\";\r\n");
      out.write("	        }\r\n");
      out.write("	     	if(");
      out.print(session.getAttribute("point"));
      out.write("< b) {\r\n");
      out.write("				b =");
      out.print(session.getAttribute("point"));
      out.write(";\r\n");
      out.write("				message = \"\";\r\n");
      out.write("			}\r\n");
      out.write("	     	var ab = (a - b + 3000);\r\n");
      out.write("			$('#ab').text(ab.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ','));\r\n");
      out.write("			$(\"#usePoint\").val(b);\r\n");
      out.write("			$('#usePointResult').text(b.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ','));\r\n");
      out.write("			$('#message').text(message);\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("function allPoint() {\r\n");
      out.write("	$(\"#usePoint\").val(");
      out.print(session.getAttribute("point"));
      out.write(");\r\n");
      out.write("	$( document ).ready( function() {\r\n");
      out.write("		var a = Number($( '#a' ).val());\r\n");
      out.write("		var b = $( '#usePoint' ).val();\r\n");
      out.write("		var message = \"\";\r\n");
      out.write("		\r\n");
      out.write("		if(a<b){\r\n");
      out.write("			b = a;\r\n");
      out.write("		    message = \"상품 가격보다 클 수 없어 최대치를 입력합니다.\";\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		var ab = a - b + 3000;\r\n");
      out.write("		$( '#ab' ).text( ab.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ',') );\r\n");
      out.write("		$(\"#usePoint\").val(b);\r\n");
      out.write("		$( '#usePointResult' ).text( b.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ',') );\r\n");
      out.write(" 		$( '#message' ).text( message );\r\n");
      out.write(" 		\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("function selectAddr(i){\r\n");
      out.write("	if(i == 0){\r\n");
      out.write("		var addr = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[0].deli_addr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("		var postcode = addr.substr(1,5);\r\n");
      out.write("		var startIndex1 = addr.indexOf(\")\")+2;\r\n");
      out.write("		var endIndex1 = addr.indexOf(\",\");	\r\n");
      out.write("		var addr1 = addr.substring(startIndex1, endIndex1);\r\n");
      out.write("		var startIndex2 = addr.indexOf(\",\")+2;\r\n");
      out.write("		var addr2 = addr.substring(startIndex2);\r\n");
      out.write("		$(\"input:text[name=deli_name]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[0].deli_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"input:text[name=deli_postcode]\").val(postcode);\r\n");
      out.write("		$(\"input:text[name=deli_addr1]\").val(addr1);\r\n");
      out.write("		$(\"input:text[name=deli_addr2]\").val(addr2);\r\n");
      out.write("		$(\"input:text[name=deli_phone]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[0].deli_phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"input:text[name=deli_msg]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[0].deli_msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"input:text[name=deli_pwd]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[0].deli_pwd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("	} else if(i == 1){\r\n");
      out.write("		var addr = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[1].deli_addr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("		var postcode = addr.substr(1,5);\r\n");
      out.write("		var startIndex1 = addr.indexOf(\")\")+2;\r\n");
      out.write("		var endIndex1 = addr.indexOf(\",\");	\r\n");
      out.write("		var addr1 = addr.substring(startIndex1, endIndex1);\r\n");
      out.write("		var startIndex2 = addr.indexOf(\",\")+2;\r\n");
      out.write("		var addr2 = addr.substring(startIndex2);\r\n");
      out.write("		$(\"input:text[name=deli_name]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[1].deli_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"input:text[name=deli_postcode]\").val(postcode);\r\n");
      out.write("		$(\"input:text[name=deli_addr1]\").val(addr1);\r\n");
      out.write("		$(\"input:text[name=deli_addr2]\").val(addr2);\r\n");
      out.write("		$(\"input:text[name=deli_phone]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[1].deli_phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"input:text[name=deli_msg]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[1].deli_msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"input:text[name=deli_pwd]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[1].deli_pwd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("	}else if(i == 2){\r\n");
      out.write("		var addr = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[2].deli_addr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("		var postcode = addr.substr(1,5);\r\n");
      out.write("		var startIndex1 = addr.indexOf(\")\")+2;\r\n");
      out.write("		var endIndex1 = addr.indexOf(\",\");	\r\n");
      out.write("		var addr1 = addr.substring(startIndex1, endIndex1);\r\n");
      out.write("		var startIndex2 = addr.indexOf(\",\")+2;\r\n");
      out.write("		var addr2 = addr.substring(startIndex2);\r\n");
      out.write("		$(\"input:text[name=deli_name]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[2].deli_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"input:text[name=deli_postcode]\").val(postcode);\r\n");
      out.write("		$(\"input:text[name=deli_addr1]\").val(addr1);\r\n");
      out.write("		$(\"input:text[name=deli_addr2]\").val(addr2);\r\n");
      out.write("		$(\"input:text[name=deli_phone]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[2].deli_phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"input:text[name=deli_msg]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[2].deli_msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"input:text[name=deli_pwd]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[2].deli_pwd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("	}else if(i == 3){\r\n");
      out.write("		var addr = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[3].deli_addr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("		var postcode = addr.substr(1,5);\r\n");
      out.write("		var startIndex1 = addr.indexOf(\")\")+2;\r\n");
      out.write("		var endIndex1 = addr.indexOf(\",\");	\r\n");
      out.write("		var addr1 = addr.substring(startIndex1, endIndex1);\r\n");
      out.write("		var startIndex2 = addr.indexOf(\",\")+2;\r\n");
      out.write("		var addr2 = addr.substring(startIndex2);\r\n");
      out.write("		$(\"input:text[name=deli_name]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[3].deli_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"input:text[name=deli_postcode]\").val(postcode);\r\n");
      out.write("		$(\"input:text[name=deli_addr1]\").val(addr1);\r\n");
      out.write("		$(\"input:text[name=deli_addr2]\").val(addr2);\r\n");
      out.write("		$(\"input:text[name=deli_phone]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[3].deli_phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"input:text[name=deli_msg]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[3].deli_msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"input:text[name=deli_pwd]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[3].deli_pwd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("	}else if(i == 4){\r\n");
      out.write("		var addr = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[4].deli_addr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("		var postcode = addr.substr(1,5);\r\n");
      out.write("		var startIndex1 = addr.indexOf(\")\")+2;\r\n");
      out.write("		var endIndex1 = addr.indexOf(\",\");	\r\n");
      out.write("		var addr1 = addr.substring(startIndex1, endIndex1);\r\n");
      out.write("		var startIndex2 = addr.indexOf(\",\")+2;\r\n");
      out.write("		var addr2 = addr.substring(startIndex2);\r\n");
      out.write("		$(\"input:text[name=deli_name]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[4].deli_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"input:text[name=deli_postcode]\").val(postcode);\r\n");
      out.write("		$(\"input:text[name=deli_addr1]\").val(addr1);\r\n");
      out.write("		$(\"input:text[name=deli_addr2]\").val(addr2);\r\n");
      out.write("		$(\"input:text[name=deli_phone]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[4].deli_phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"input:text[name=deli_msg]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[4].deli_msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("		$(\"input:text[name=deli_pwd]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alist[4].deli_pwd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("	}\r\n");
      out.write("	modal.classList.toggle('show');\r\n");
      out.write("	body.style.overflow = 'auto'\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function selectMyAddr(i){\r\n");
      out.write("	if(i == 0){\r\n");
      out.write("	var name = manage.document.getElementById('name_0').value;\r\n");
      out.write("	$(\"input:text[name=deli_name]\").val(name);\r\n");
      out.write("	var addr = manage.document.getElementById('addr_0').value;\r\n");
      out.write("	var postcode = addr.substr(1,5);\r\n");
      out.write("	var startIndex1 = addr.indexOf(\")\")+2;\r\n");
      out.write("	var endIndex1 = addr.indexOf(\",\");	\r\n");
      out.write("	var addr1 = addr.substring(startIndex1, endIndex1);\r\n");
      out.write("	var startIndex2 = addr.indexOf(\",\")+2;\r\n");
      out.write("	var addr2 = addr.substring(startIndex2);\r\n");
      out.write("	var phone = manage.document.getElementById('phone_0').value;\r\n");
      out.write("	var msg = manage.document.getElementById('msg_0').value;\r\n");
      out.write("	var pwd = manage.document.getElementById('pwd_0').value;\r\n");
      out.write("	$(\"input:text[name=deli_postcode]\").val(postcode);\r\n");
      out.write("	$(\"input:text[name=deli_addr1]\").val(addr1);\r\n");
      out.write("	$(\"input:text[name=deli_addr2]\").val(addr2);\r\n");
      out.write("	$(\"input:text[name=deli_phone]\").val(phone);\r\n");
      out.write("	$(\"input:text[name=deli_msg]\").val(msg);\r\n");
      out.write("	$(\"input:text[name=deli_pwd]\").val(pwd);\r\n");
      out.write("	} else if(i == 1){\r\n");
      out.write("	var name = manage.document.getElementById('name_1').value;\r\n");
      out.write("	$(\"input:text[name=deli_name]\").val(name);\r\n");
      out.write("	var addr = manage.document.getElementById('addr_1').value;\r\n");
      out.write("	var postcode = addr.substr(1,5);\r\n");
      out.write("	var startIndex1 = addr.indexOf(\")\")+2;\r\n");
      out.write("	var endIndex1 = addr.indexOf(\",\");	\r\n");
      out.write("	var addr1 = addr.substring(startIndex1, endIndex1);\r\n");
      out.write("	var startIndex2 = addr.indexOf(\",\")+2;\r\n");
      out.write("	var addr2 = addr.substring(startIndex2);\r\n");
      out.write("	var phone = manage.document.getElementById('phone_1').value;\r\n");
      out.write("	var msg = manage.document.getElementById('msg_1').value;\r\n");
      out.write("	var pwd = manage.document.getElementById('pwd_1').value;\r\n");
      out.write("	$(\"input:text[name=deli_postcode]\").val(postcode);\r\n");
      out.write("	$(\"input:text[name=deli_addr1]\").val(addr1);\r\n");
      out.write("	$(\"input:text[name=deli_addr2]\").val(addr2);\r\n");
      out.write("	$(\"input:text[name=deli_phone]\").val(phone);\r\n");
      out.write("	$(\"input:text[name=deli_msg]\").val(msg);\r\n");
      out.write("	$(\"input:text[name=deli_pwd]\").val(pwd);\r\n");
      out.write("	} else if(i == 2){\r\n");
      out.write("	var name = manage.document.getElementById('name_2').value;\r\n");
      out.write("	$(\"input:text[name=deli_name]\").val(name);\r\n");
      out.write("	var addr = manage.document.getElementById('addr_2').value;\r\n");
      out.write("	var postcode = addr.substr(1,5);\r\n");
      out.write("	var startIndex1 = addr.indexOf(\")\")+2;\r\n");
      out.write("	var endIndex1 = addr.indexOf(\",\");	\r\n");
      out.write("	var addr1 = addr.substring(startIndex1, endIndex1);\r\n");
      out.write("	var startIndex2 = addr.indexOf(\",\")+2;\r\n");
      out.write("	var addr2 = addr.substring(startIndex2);\r\n");
      out.write("	var phone = manage.document.getElementById('phone_2').value;\r\n");
      out.write("	var msg = manage.document.getElementById('msg_2').value;\r\n");
      out.write("	var pwd = manage.document.getElementById('pwd_2').value;\r\n");
      out.write("	$(\"input:text[name=deli_postcode]\").val(postcode);\r\n");
      out.write("	$(\"input:text[name=deli_addr1]\").val(addr1);\r\n");
      out.write("	$(\"input:text[name=deli_addr2]\").val(addr2);\r\n");
      out.write("	$(\"input:text[name=deli_phone]\").val(phone);\r\n");
      out.write("	$(\"input:text[name=deli_msg]\").val(msg);\r\n");
      out.write("	$(\"input:text[name=deli_pwd]\").val(pwd);\r\n");
      out.write("	} else if(i == 3){\r\n");
      out.write("		var name = manage.document.getElementById('name_3').value;\r\n");
      out.write("		$(\"input:text[name=deli_name]\").val(name);\r\n");
      out.write("		var addr = manage.document.getElementById('addr_3').value;\r\n");
      out.write("		var postcode = addr.substr(1,5);\r\n");
      out.write("		var startIndex1 = addr.indexOf(\")\")+2;\r\n");
      out.write("		var endIndex1 = addr.indexOf(\",\");	\r\n");
      out.write("		var addr1 = addr.substring(startIndex1, endIndex1);\r\n");
      out.write("		var startIndex2 = addr.indexOf(\",\")+2;\r\n");
      out.write("		var addr2 = addr.substring(startIndex2);\r\n");
      out.write("		var phone = manage.document.getElementById('phone_3').value;\r\n");
      out.write("		var msg = manage.document.getElementById('msg_3').value;\r\n");
      out.write("		var pwd = manage.document.getElementById('pwd_3').value;\r\n");
      out.write("		$(\"input:text[name=deli_postcode]\").val(postcode);\r\n");
      out.write("		$(\"input:text[name=deli_addr1]\").val(addr1);\r\n");
      out.write("		$(\"input:text[name=deli_addr2]\").val(addr2);\r\n");
      out.write("		$(\"input:text[name=deli_phone]\").val(phone);\r\n");
      out.write("		$(\"input:text[name=deli_msg]\").val(msg);\r\n");
      out.write("		$(\"input:text[name=deli_pwd]\").val(pwd);\r\n");
      out.write("	} else if(i == 4){\r\n");
      out.write("		var name = manage.document.getElementById('name_4').value;\r\n");
      out.write("		$(\"input:text[name=deli_name]\").val(name);\r\n");
      out.write("		var addr = manage.document.getElementById('addr_4').value;\r\n");
      out.write("		var postcode = addr.substr(1,5);\r\n");
      out.write("		var startIndex1 = addr.indexOf(\")\")+2;\r\n");
      out.write("		var endIndex1 = addr.indexOf(\",\");	\r\n");
      out.write("		var addr1 = addr.substring(startIndex1, endIndex1);\r\n");
      out.write("		var startIndex2 = addr.indexOf(\",\")+2;\r\n");
      out.write("		var addr2 = addr.substring(startIndex2);\r\n");
      out.write("		var phone = manage.document.getElementById('phone_4').value;\r\n");
      out.write("		var msg = manage.document.getElementById('msg_4').value;\r\n");
      out.write("		var pwd = manage.document.getElementById('pwd_4').value;\r\n");
      out.write("		$(\"input:text[name=deli_postcode]\").val(postcode);\r\n");
      out.write("		$(\"input:text[name=deli_addr1]\").val(addr1);\r\n");
      out.write("		$(\"input:text[name=deli_addr2]\").val(addr2);\r\n");
      out.write("		$(\"input:text[name=deli_phone]\").val(phone);\r\n");
      out.write("		$(\"input:text[name=deli_msg]\").val(msg);\r\n");
      out.write("		$(\"input:text[name=deli_pwd]\").val(pwd);\r\n");
      out.write("	}\r\n");
      out.write("	modal.classList.toggle('show');\r\n");
      out.write("	body.style.overflow = 'auto'\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("/* number값 화살표 없애기 */\r\n");
      out.write("input[type=\"number\"]::-webkit-outer-spin-button,\r\n");
      out.write("input[type=\"number\"]::-webkit-inner-spin-button {\r\n");
      out.write("    -webkit-appearance: none;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write("button{\r\n");
      out.write("border: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart table{\r\n");
      out.write("border:1px solid orange;\r\n");
      out.write("text-align:center;\r\n");
      out.write("width:100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart th{\r\n");
      out.write("background-color:orange;\r\n");
      out.write("border:1px solid orange;\r\n");
      out.write("}\r\n");
      out.write(".cart td{\r\n");
      out.write("border:1px solid orange;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#deli_addr table{\r\n");
      out.write("border:1px solid orange;\r\n");
      out.write("text-align:left;\r\n");
      out.write("width:100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#deli_addr th{\r\n");
      out.write("background-color:orange;\r\n");
      out.write("border:1px solid orange;\r\n");
      out.write("}\r\n");
      out.write("#deli_addr td{\r\n");
      out.write("border:1px solid orange;\r\n");
      out.write("} \r\n");
      out.write("/* CSS RESET */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".full-bg {\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table {\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	display: table;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-cell {\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	display: table-cell;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-container {\r\n");
      out.write("	width: 1000px;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	padding: 70px 20px;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login--title {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-btn {\r\n");
      out.write("	display: block;\r\n");
      out.write("	width: 30%;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	background-color: #fd7e14;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	margin: 5px 0;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	border:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-btn:hover {\r\n");
      out.write("	background-color: #FF9900;\r\n");
      out.write("	box-shadow: 3px 3px 3px rgba(0, 0, 0, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	display: none;\r\n");
      out.write("	background-color: rgba(0, 0, 0, 0.4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal.show {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal_body {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 50%;\r\n");
      out.write("	left: 50%;\r\n");
      out.write("	width: 600px;\r\n");
      out.write("	height: 800px;\r\n");
      out.write("	padding: 40px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	background-color: rgb(255, 255, 255);\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	box-shadow: 0 2px 3px 0 rgba(34, 36, 38, 0.15);\r\n");
      out.write("	transform: translateX(-50%) translateY(-50%);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "nav.jsp", out, false);
      out.write("\r\n");
      out.write("		<div style=\"width:60%;margin-left: auto; margin-right: auto;\">\r\n");
      out.write("		<form action=\"payment.jsp\" method=\"post\" name=\"frm\" id=\"frm\">\r\n");
      out.write("	\r\n");
      out.write("		<div class=\"cart\">\r\n");
      out.write("		<hr>\r\n");
      out.write("		<!-- 장바구니 리스트 출력  -->\r\n");
      out.write("		<h2><i class=\"bi-journal-check\"></i> 결제정보</h2>\r\n");
      out.write("		<div align=\"right\">\r\n");
      out.write("		<span style=\"color:gray\">01 장바구니 <i class=\"bi-caret-right-fill\"></i></span>\r\n");
      out.write("		<span style=\"color:black\"><strong> 02 주문서작성/결제 <i class=\"bi-caret-right-fill\"></i></strong></span>\r\n");
      out.write("		<span style=\"color:gray\"> 03 주문완료 </span>\r\n");
      out.write("		</div>\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th style=\"width:75px\"><!-- 이미지 --></th>\r\n");
      out.write("					<th>상품정보</th>\r\n");
      out.write("					<th>판매금액</th>\r\n");
      out.write("					<th>수량</th>\r\n");
      out.write("					<th>합 금액</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("				");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("<!-- 주문자 정보  -->\r\n");
      out.write("		</div>\r\n");
      out.write("			<div align=\"center\">\r\n");
      out.write("				<div class=\"login-container\">\r\n");
      out.write("					<div align=\"left\">\r\n");
      out.write("						<h3><i class=\"bi-list-check\"></i> 주문자 정보</h3>\r\n");
      out.write("						<table>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th>주문하시는 분</th>\r\n");
      out.write("								<td>");
      out.print(session.getAttribute("name"));
      out.write("</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th>휴대폰 번호</th>\r\n");
      out.write("								<td>");
      out.print(session.getAttribute("phone"));
      out.write("</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th>이메일</th>\r\n");
      out.write("								<td>");
      out.print(session.getAttribute("email"));
      out.write("\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("						<br>\r\n");
      out.write("						<hr>\r\n");
      out.write("						<br>\r\n");
      out.write("						<!-- 배송정보 작성  -->\r\n");
      out.write("						<h3><i class=\"bi-list-check\"></i> 배송정보</h3>\r\n");
      out.write("						<table>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th>배송지 확인</th>\r\n");
      out.write("								<td>주문자정보와 동일<input type=\"radio\" id=\"addrCheck1\" name=\"addrCheck\" value=\"0\" checked>\r\n");
      out.write("									직접입력<input type=\"radio\" id=\"addrCheck2\" name=\"addrCheck\"	value=\"1\">\r\n");
      out.write("\r\n");
      out.write("									\r\n");
      out.write("									<button type=\"button\" class=\"btn-open-popup\">배송지 변경</button>\r\n");
      out.write("									<div class=\"modal\">\r\n");
      out.write("											<div class=\"modal_body\">\r\n");
      out.write("									<input type=\"button\" name=\"modal\" id=\"modal1\" onclick=\"modalDisplay1()\" value=\"나의 배송지\">\r\n");
      out.write("									<input type=\"button\" name=\"modal\" id=\"modal2\" onclick=\"modalDisplay2()\" value=\"최근 배송지\">\r\n");
      out.write("											<div id=\"manage\">\r\n");
      out.write("											<br>\r\n");
      out.write("												<iframe id=\"frame\" name=\"manage\" src=\"addrmanage.do\" frameborder=\"0\" scrolling=\"no\"\r\n");
      out.write("													width=\"500\" height=\"700\"></iframe>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div id=\"recent\" style=\"display:none\">\r\n");
      out.write("											<br>\r\n");
      out.write("												최근 배송지\r\n");
      out.write("												<hr>\r\n");
      out.write("												<!-- 최근 배송지  -->\r\n");
      out.write("												");

													if ((int) session.getAttribute("addrcnt") != 0) {
												
      out.write("\r\n");
      out.write("												<table width=\"100%\">\r\n");
      out.write("													");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("												</table>\r\n");
      out.write("												<hr> 최근 배송지는 5개까지 저장됩니다.\r\n");
      out.write("												");

													} else {
												
      out.write("\r\n");
      out.write("														<div align=\"center\">\r\n");
      out.write("															<i style=\"font-size:200px;color:orange\" class=\"bi-geo-alt-fill\"></i>\r\n");
      out.write("															<div style=\"font-size:30px;color:gray\">최근 배송지가 없습니다.</div>\r\n");
      out.write("														</div>\r\n");
      out.write("												");

													}
												
      out.write("\r\n");
      out.write("\r\n");
      out.write("												<hr>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("										<script>\r\n");
      out.write("									const body = document.querySelector('body');\r\n");
      out.write("									const modal = document.querySelector('.modal');\r\n");
      out.write("									const btnOpenPopup = document.querySelector('.btn-open-popup');\r\n");
      out.write("\r\n");
      out.write("									btnOpenPopup.addEventListener('click', () => {\r\n");
      out.write("										\r\n");
      out.write("									/* 버튼 클릭시 라디오 버튼 체크 해제 */\r\n");
      out.write("									  document.getElementById('addrCheck1').checked = false\r\n");
      out.write("									  document.getElementById('addrCheck2').checked = false\r\n");
      out.write("									\r\n");
      out.write("									  modal.classList.toggle('show');\r\n");
      out.write("									  if (modal.classList.contains('show')) {\r\n");
      out.write("									    body.style.overflow = 'hidden';\r\n");
      out.write("									  }\r\n");
      out.write("									});\r\n");
      out.write("\r\n");
      out.write("									modal.addEventListener('click', (event) => {\r\n");
      out.write("									  if (event.target === modal) {\r\n");
      out.write("									    modal.classList.toggle('show');\r\n");
      out.write("\r\n");
      out.write("									    if (!modal.classList.contains('show')) {\r\n");
      out.write("									      body.style.overflow = 'auto';\r\n");
      out.write("									    }\r\n");
      out.write("									  }\r\n");
      out.write("									});\r\n");
      out.write("									</script></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th>받으실 분</th>\r\n");
      out.write("								<td><input type=\"text\" id=\"name\" class=\"reset1\" name=\"deli_name\" readonly value=\"");
      out.print(session.getAttribute("name"));
      out.write("\" required></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th>받으실 곳</th>\r\n");
      out.write("								<td><input type=\"text\" name=\"deli_postcode\"id=\"sample4_postcode\" value=\"");
      out.print(postcode);
      out.write("\" placeholder=\"우편번호\" size=\"5\" readonly required>\r\n");
      out.write("								<input type=\"button\" id=\"daumPostCode\" onclick=\"sample4_execDaumPostcode()\" value=\"우편번호 찾기\" disabled><br>\r\n");
      out.write("								<input type=\"text\" name=\"deli_addr1\" id=\"sample4_roadAddress\"  value=\"");
      out.print(addr1);
      out.write("\" placeholder=\"도로명주소\" size=\"30\" readonly required><br>\r\n");
      out.write("								<input type=\"text\" name=\"deli_addr2\" id=\"sample4_detailAddress\" value=\"");
      out.print(addr2);
      out.write("\"  placeholder=\"상세주소\" readonly required><br>\r\n");
      out.write("								<span id=\"guide\" style=\"color:#999;display:none\"></span>\r\n");
      out.write("								<input type=\"hidden\" id=\"sample4_jibunAddress\" placeholder=\"지번주소\">\r\n");
      out.write("								<input type=\"hidden\" id=\"sample4_extraAddress\" placeholder=\"참고항목\">\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th>휴대폰 번호</th>\r\n");
      out.write("								<td><input type=\"text\" name=\"deli_phone\" readonly value=\"");
      out.print(session.getAttribute("phone"));
      out.write("\" required></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th>배달 참고메세지</th>\r\n");
      out.write("								<td><input type=\"text\" name=\"deli_msg\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th>포인트</th>\r\n");
      out.write("								<td>\r\n");
      out.write("								<input id=\"a\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("								<input id=\"usePoint\" type=\"number\" min=\"0\" max=\"");
      out.print(session.getAttribute("point"));
      out.write("\" name=\"usePoint\" value=\"0\" required>\r\n");
      out.write("								사용가능한 포인트 : ");
      out.print(session.getAttribute("point"));
      out.write("p<br>\r\n");
      out.write("								<div style=\"color:red\"><span id=\"message\"></span></div>\r\n");
      out.write("								<input type=\"button\" onclick=\"allPoint()\" value=\"전부 사용\">\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("						<br>\r\n");
      out.write("						\r\n");
      out.write("						<hr>\r\n");
      out.write("						<br>\r\n");
      out.write("						<h3><i class=\"bi-list-check\"></i> 공동현관 출입방법</h3>\r\n");
      out.write("						<table>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th>출입방법</th>\r\n");
      out.write("								<td>공동출입문\r\n");
      out.write("								<input type=\"radio\" name=\"deli\" id=\"deli1\" onchange=\"setDisplay()\" checked>\r\n");
      out.write("								별도 출입제한 없음\r\n");
      out.write("								<input type=\"radio\" name=\"deli\" id=\"deli2\" onchange=\"setDisplay()\">\r\n");
      out.write("								<div id=\"divId\">\r\n");
      out.write("									<input type=\"text\" name=\"deli_pwd\" size=\"40\" placeholder=\"예) #1234*/ 열쇠버튼+abcd+OK버튼\">\r\n");
      out.write("									</div>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("					<br>\r\n");
      out.write("					<hr>\r\n");
      out.write("					<br>\r\n");
      out.write("					<div>\r\n");
      out.write("					<h2>최종 결제 금액</h2>\r\n");
      out.write("					<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					상품가격 ");
      if (_jspx_meth_fmt_005fformatNumber_005f2(_jspx_page_context))
        return;
      out.write("원 \r\n");
      out.write("					- 사용할 포인트 <span id=\"usePointResult\"></span>p \r\n");
      out.write("					+ 배송비 ");
      if (_jspx_meth_fmt_005fformatNumber_005f3(_jspx_page_context))
        return;
      out.write("원<br>\r\n");
      out.write("					<h2><strong>=<span id=\"ab\"></span>원</strong>입니다.</h2><br>\r\n");
      out.write("					");
      if (_jspx_meth_fmt_005fparseNumber_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					적립될 포인트 : ");
      if (_jspx_meth_fmt_005fformatNumber_005f4(_jspx_page_context))
        return;
      out.write("p\r\n");
      out.write("					</div>\r\n");
      out.write("					<br>\r\n");
      out.write("					<input type=\"checkbox\" required>(필수) 구매하실 상품의 결제정보를 확인하였으며, 구매진행에 동의합니다.\r\n");
      out.write("\r\n");
      out.write("					<input type=\"hidden\" name=\"item_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${clist[0].item_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					<input type=\"hidden\" name=\"userid\" value=\"");
      out.print(session.getAttribute("userid"));
      out.write("\">\r\n");
      out.write("					<input type=\"hidden\" name=\"total_price\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result+3000}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					<input type=\"hidden\" name=\"deli_status\" value=\"결제 완료\">\r\n");
      out.write("					<input type=\"hidden\" name=\"point\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${point}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					<input type=\"submit\" id=\"submit\" class=\"form-btn\" value=\"결제\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>	\r\n");
      out.write("	<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /purchase.jsp(464,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("result");
      // /purchase.jsp(464,4) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/purchase.jsp(464,4) '0'",_jsp_getExpressionFactory().createValueExpression("0",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /purchase.jsp(465,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("cart");
      // /purchase.jsp(465,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/purchase.jsp(465,4) '${clist}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${clist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					<tr>\r\n");
            out.write("						<td><img alt=\"이미지\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.item_pictureUrl1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" width=\"75px\" height=\"75px\"></td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.item_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td>");
            if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("원</td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.item_cnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td>");
            if (_jspx_meth_fmt_005fformatNumber_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("원</td>\r\n");
            out.write("					</tr>\r\n");
            out.write("					");
            if (_jspx_meth_c_005fset_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("					<input type=\"hidden\" name=\"item_cnt[]\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.item_cnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("					<input type=\"hidden\" name=\"item_num[]\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.item_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /purchase.jsp(469,10) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.item_price}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /purchase.jsp(469,10) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("#,##0");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /purchase.jsp(471,10) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.item_price*cart.item_cnt}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
      _jspx_th_fmt_005fformatNumber_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /purchase.jsp(473,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("result");
      // /purchase.jsp(473,5) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/purchase.jsp(473,5) '${result+(cart.item_price*cart.item_cnt)}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${result+(cart.item_price*cart.item_cnt)}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fstep_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /purchase.jsp(529,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("addr");
      // /purchase.jsp(529,13) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/purchase.jsp(529,13) '${alist}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${alist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /purchase.jsp(529,13) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(0);
      // /purchase.jsp(529,13) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(4);
      // /purchase.jsp(529,13) name = step type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setStep(1);
      // /purchase.jsp(529,13) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVarStatus("i");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("														<tr align=\"left\">\r\n");
            out.write("															<td ><i style=\"font-size: 20px; color: orange\"\r\n");
            out.write("																class=\"bi-geo-alt-fill\"></i> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addr.deli_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("														</tr>\r\n");
            out.write("														<tr>\r\n");
            out.write("															<td align=\"left\" width=\"85%\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addr.deli_addr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("															<td width=\"15%\">\r\n");
            out.write("																<button type=\"button\"\r\n");
            out.write("																	onclick=\"selectAddr('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\">선택</button>\r\n");
            out.write("															</td>\r\n");
            out.write("														</tr>\r\n");
            out.write("														<tr>\r\n");
            out.write("															<td>　</td>\r\n");
            out.write("														</tr>\r\n");
            out.write("													");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fstep_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f2_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f2.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f2.setParent(null);
      // /purchase.jsp(650,10) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatNumber_005f2 = _jspx_th_fmt_005fformatNumber_005f2.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f2);
      _jspx_th_fmt_005fformatNumber_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f2, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f3 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f3_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f3.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f3.setParent(null);
      // /purchase.jsp(652,11) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f3.setValue("3000");
      int _jspx_eval_fmt_005fformatNumber_005f3 = _jspx_th_fmt_005fformatNumber_005f3.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f3);
      _jspx_th_fmt_005fformatNumber_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f3, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fparseNumber_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:parseNumber
    org.apache.taglibs.standard.tag.rt.fmt.ParseNumberTag _jspx_th_fmt_005fparseNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.ParseNumberTag) _005fjspx_005ftagPool_005ffmt_005fparseNumber_0026_005fvar_005fvalue_005fintegerOnly_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.ParseNumberTag.class);
    boolean _jspx_th_fmt_005fparseNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fparseNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fparseNumber_005f0.setParent(null);
      // /purchase.jsp(654,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fparseNumber_005f0.setVar("point");
      // /purchase.jsp(654,5) name = integerOnly type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fparseNumber_005f0.setIntegerOnly(true);
      // /purchase.jsp(654,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fparseNumber_005f0.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result/100*5}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fparseNumber_005f0 = _jspx_th_fmt_005fparseNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fparseNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fparseNumber_0026_005fvar_005fvalue_005fintegerOnly_005fnobody.reuse(_jspx_th_fmt_005fparseNumber_005f0);
      _jspx_th_fmt_005fparseNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fparseNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fparseNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f4 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f4_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f4.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f4.setParent(null);
      // /purchase.jsp(655,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${point}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatNumber_005f4 = _jspx_th_fmt_005fformatNumber_005f4.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f4);
      _jspx_th_fmt_005fformatNumber_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f4, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f4_reused);
    }
    return false;
  }
}
